affinityCookieTtlSec: 0
backends:
- balancingMode: UTILIZATION
  capacityScaler: 1.0
  group: https://www.googleapis.com/compute/beta/projects/ymail-compute-prj-1/zones/europe-west1-b/instanceGroups/sannew-igm-1
- balancingMode: UTILIZATION
  capacityScaler: 1.0
  group: https://www.googleapis.com/compute/beta/projects/ymail-compute-prj-1/zones/us-central1-c/instanceGroups/sannew-igm-2
connectionDraining:
  drainingTimeoutSec: 300
creationTimestamp: '2025-05-28T12:37:05.172-07:00'
description: ''
enableCDN: false
fingerprint: r4yUzgiRdoI=
healthChecks:
- https://www.googleapis.com/compute/beta/projects/ymail-compute-prj-1/global/healthChecks/sannew-tcp-hc
kind: compute#backendService
loadBalancingScheme: EXTERNAL_MANAGED
name: sannew-app-bs
port: 80
portName: sannew-https
protocol: HTTPS
selfLink: https://www.googleapis.com/compute/beta/projects/ymail-compute-prj-1/global/backendServices/sannew-app-bs
sessionAffinity: NONE
timeoutSec: 10
tlsSettings:
  authenticationConfig: //networksecurity.googleapis.com/projects/ymail-compute-prj-1/locations/global/backendAuthenticationConfigs/sannew-backend-auth-config
  sni: examplebackeendsvc.com
  subjectAltNames:
  - dnsName: examplebackeendsvc.com
  - dnsName: api.examplebackeendsvc.com
usedBy:
- reference: https://www.googleapis.com/compute/beta/projects/ymail-compute-prj-1/global/urlMaps/sannew-url-map
